/*
 * Filename     : Menu.java
 * Programmer   : Sekar Madu Kusumawardani
 * Date         : 2022-06-14
 * Email        : sekarmadu99@gmail.com
 * Website      : https://sekarmk03.github.io/
 * Deskripsi    : kelas Menu untuk membuat tampilan menu
*/

package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import model.TableExperiences;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
// mengakses package viewmodel
import viewmodel.Game;
import viewmodel.Sound;


/**
 *
 * @author sekar
 */
public class Menu extends javax.swing.JFrame {
    // properti
    public Game game; // objek game
    private TableExperiences texperiences; // data tabel
    public Clip audio; // backsound
    private String username; // username
    
    public Menu() {
        // konstruktor
        initComponents(); // load component
        this.username = ""; // inisialisasi username
        try {
            // membuat tabel baru
            this.texperiences = new TableExperiences();
            // diisi dgn data dari database
            TableExperiences.setModel(texperiences.setTable());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // memutar suara di menu awal
        Sound bgm = new Sound();
        audio = bgm.playSound(this.audio, "01_Game_Start.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        lblMenuTitle = new javax.swing.JLabel();
        lblCopy = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableExperiences = new javax.swing.JTable();
        lblNewUsername = new javax.swing.JLabel();
        TFUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Survive Hop | Menu");
        setBackground(new java.awt.Color(51, 153, 255));
        setName("Main Menu"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Keep on surviving!");

        btnPlay.setBackground(new java.awt.Color(51, 255, 102));
        btnPlay.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lblMenuTitle.setFont(new java.awt.Font("Bunny Funny", 1, 36)); // NOI18N
        lblMenuTitle.setForeground(java.awt.Color.white);
        lblMenuTitle.setText("THE SURVIVE HOP");
        lblMenuTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMenuTitle.setAlignmentY(0.0F);
        lblMenuTitle.setIconTextGap(0);

        lblCopy.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblCopy.setForeground(new java.awt.Color(236, 245, 255));
        lblCopy.setText("2007703 - Sekar Madu K.");

        btnQuit.setBackground(new java.awt.Color(255, 102, 102));
        btnQuit.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        TableExperiences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        TableExperiences.setName(""); // NOI18N
        TableExperiences.setPreferredSize(new java.awt.Dimension(225, 200));
        TableExperiences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableExperiencesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableExperiences);

        lblNewUsername.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblNewUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblNewUsername.setText("Input Username baru atau pilih dari tabel");

        TFUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFUsername.setToolTipText("Username...");
        TFUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCopy)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFUsername)
                                    .addComponent(lblMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblNewUsername)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblMenuTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNewUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblCopy)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:    
        if(this.username.length() == 0 && TFUsername.getText().length() != 0) {
            // jika nilai username masih kosong
            // dan text field TFUsername ada isinya
            this.username = TFUsername.getText();
        }
        if(TFUsername.getText().length() == 0 && this.username.length() == 0) {
            // jika text field kosong
            // dan nilai username masih kosong (tidak klik dari tabel)
            JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!\nPilih user atau masukkan username baru.");
        } else {
            // sound new game
            Sound bgm = new Sound();
            bgm.stopSound(this.audio);
            
            // buat game baru
            game = new Game();
            GameWindow gw = new GameWindow(game); // buat window
            game.setUsername(this.username); // set username
            // cek apakah username sudah ada di database
            TableExperiences temp = null;
            try {
                temp = new TableExperiences();
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            temp.getDataTExperiences(this.username);
            int c = 0, tadapt = 0, tfall = 0;
            try {
                while(temp.getResult().next()){
                    // jika username sudah ada di database,
                    // ambil nilai adapt dan fall nya
                    tadapt = Integer.parseInt(temp.getResult().getString(3));
                    tfall = Integer.parseInt(temp.getResult().getString(4));
                    c++;
                }
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            // set score adapt dan fall di awal game
            if(c == 0){
                // jika user baru, adapt dan fall 0
                game.setScore(0,0);
            } else {
                // jika user lama, adapt dan fall akumulasi
                game.setScore(tadapt, tfall);
            }
            
            // game dimulai
            game.StartGame(gw);
            this.setVisible(false); // menu window dibuat invisible
            this.dispose(); // menu window di clear
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void TableExperiencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableExperiencesMouseClicked
        // TODO add your handling code here:
        // jika salah satu record dalam tabel di klik
        int row = TableExperiences.getSelectedRow();
        // set username dengan username pada tabel yg di klik
        this.username = TableExperiences.getModel().getValueAt(row, 0).toString();
    }//GEN-LAST:event_TableExperiencesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFUsername;
    private javax.swing.JTable TableExperiences;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCopy;
    private javax.swing.JLabel lblMenuTitle;
    private javax.swing.JLabel lblNewUsername;
    // End of variables declaration//GEN-END:variables
}
